"""Set Nullable to donation comment

Revision ID: c2445e08509c
Revises: 04bfe27f21bf
Create Date: 2023-12-21 00:11:33.591519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2445e08509c'
down_revision = '04bfe27f21bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
