"""Add default to close_data

Revision ID: 4369389d516d
Revises: 7177ba14c10f
Create Date: 2023-12-20 20:57:55.471907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4369389d516d'
down_revision = '7177ba14c10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
