"""Set Nullable to close_data

Revision ID: 04bfe27f21bf
Revises: 4369389d516d
Create Date: 2023-12-20 22:57:33.110161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04bfe27f21bf'
down_revision = '4369389d516d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
